Console.BackgroundColor = ConsoleColor.DarkRed;
Console.ForegroundColor = ConsoleColor.White;
Console.WriteLine("Se for pra ser - Lagum");
Console.ResetColor();
Console.WriteLine();
Console.WriteLine("Pensando bem, já fomos um");
Console.WriteLine("Hoje sou só parte do que já se foi");
Console.WriteLine("Divididos somos dois");
Console.WriteLine("Com vontade do tempo que eram um");
Console.WriteLine();
Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine("Se for pra ser");
Console.WriteLine("Não será do jeito que você quiser");
Console.WriteLine("Se for pra ser");
Console.WriteLine("Não será do jeito que você quiser");
Console.ResetColor();
Console.WriteLine();
Console.WriteLine("Eu quase esqueço do seu rosto");
Console.WriteLine("Eu nem me lembro mais");
Console.WriteLine("Tanto tempo faz que eu ouvi sua voz");
Console.WriteLine("Já pensei se eu te encontro nessa rua");
Console.WriteLine("Onde eu me acostumei a te esperar");
Console.WriteLine();
Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine("Se for pra ser");
Console.WriteLine("Não será do jeito que você quiser");
Console.WriteLine("Se for pra ser");
Console.WriteLine("Não será do jeito que você quiser");
Console.ResetColor();